version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_IP}
      KAFKA_PORT: 9092
      KAFKA_BROKER_ID: 1
    volumes:
      - ./ssl:/ssl
  kafka2:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_IP}
      KAFKA_PORT: 9093
      KAFKA_BROKER_ID: 2
    volumes:
      - ./ssl:/ssl
  kafka3:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_IP}
      KAFKA_PORT: 9094
      KAFKA_BROKER_ID: 3
    volumes:
      - ./ssl:/ssl
